server:
  port: 8080

spring:
  profiles:
    active: local

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    suffix: .html

  #DB configuration
  mybatis:
    configuration:
      map-underscore-to-camel-case: true
    mapper-locations:
      - mapper/*.xml
    type-aliases-package: io.system.heeseong.*

