server:
  port: 8080

spring:
  profiles:
    active: local

  devtools:
    livereload:
      enabled: true

  thymeleaf:
    cache: false
    enabled: true
    encoding: UTF-8
    suffix: .html

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
      #ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: always
      encoding: UTF-8
      schema-locations: classpath:sql/data.sql

  #DB configuration
  mybatis:
    configuration:
      map-underscore-to-camel-case: true
    mapper-locations:
      - mapper/*.xml
    type-aliases-package: io.system.heeseong.*

